### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by 0xr00tf3rr3t** [triple82/Portfolio#1]
- [Missing semicolon at the end of line 96](https://github.com/triple82/Portfolio/blob/bd9745d5165e8e1ff5a813ca6865a5ca619b7f0d/main.css#L96)
- [Missing semicolon and valued at end of line 72 ](https://github.com/triple82/Portfolio/blob/bd9745d5165e8e1ff5a813ca6865a5ca619b7f0d/main.css#L72)
- [Missing semicolon at the end of line 41](https://github.com/triple82/Portfolio/blob/bd9745d5165e8e1ff5a813ca6865a5ca619b7f0d/main.css#L41)
-

**Comment by triple82** [comment]
Thank you for your help with this!
